### PR TITLE
fixed #12

### LINKED ISSUE #12: Install script doesn't read checksums correctly
In recent updates of the actions for releasing lega-commander changes the naming conventions of OS names. This seems to break the install script even though it should be adjusting for the character case variations.

### PR DESCRIPTION
**Pull request by joshbaskaran**

### CODE REVIEW

**Comment by pavelvazquez** [comment]
It does install on mac. 

I also tried on a Linux VM with Ubuntu 18.04. It attempts to download **lega-commander_Linux_amd64.tar.gz**, which isn't included in the release. Is this not supported?

This is the error: 

```
$ ./install.sh -d
elixir-oslo/lega-commander info checking GitHub for latest tag
elixir-oslo/lega-commander debug http_download https://github.com/elixir-oslo/lega-commander/releases/latest
elixir-oslo/lega-commander info found version: 1.1.3 for v1.1.3/Linux/amd64
elixir-oslo/lega-commander debug downloading files into /tmp/tmp.I6PA2VT2va
elixir-oslo/lega-commander debug http_download https://github.com/elixir-oslo/lega-commander/releases/download/v1.1.3/lega-commander_Linux_amd64.tar.gz
elixir-oslo/lega-commander debug http_download_curl received HTTP status 404
```

**Comment by kjellp** [comment]
I downloaded the install.sh version in the "12-install-script-checksum-validation" (linked to this PR#13), and ran the install script with a local binary directory on my Linux (Ubuntu 18.04) laptop: no errors, but no binary installed either. Also tried with default location (/usr/local/bin), same result...
image

**Comment by joshbaskaran** [comment]
I see the issue here. The goreleaser also switched out amd64 with x86_64.

**Comment by kjellp** [comment]
Tested again on linux (with user defined bindir), worked like a charm now.

**Review by kjellp — APPROVED** [review]
Tested on Linux, LGTM. Others will test Mac and Windows so I'll approve for my testing.

**Pull request merged**
